[build]
packages = [
    "pyroll"
]

[version]
path = "pyroll/stationary_thermal_analysis_work_roll/__init__.py"

[envs.default]
path = ".venv"
dependencies = [
    "pytest ~= 7.0"
]

[envs.docs]
path = ""
dependencies = [
    "pygments ~= 2.0"
]

[envs.docs.scripts]
build = "latexmk --cd --pdf --shell-escape docs/docs" # compile LaTeX docs with latexmk

[envs.test]
path = ""

[envs.test.scripts]
all = "pytest"

[[envs.test.matrix]]
python = ["3.9", "3.10", "3.11"]